---

- name: Install language-pack-ja.
  apt:
    name: "{{ common.locale.packages }}"
    state: present

- name: Generate japanese locale ja_JP.UTF-8.
  locale_gen:
    name: ja_JP.UTF-8

#- name: Set locale to ja_JP.UTF-8
#  command: update-locale LANG=ja_JP.UTF-8
#  when: ansible_env.LANG | default('') != 'ja_JP.UTF-8'
