---

# ref. https://gryzli.info/2017/12/21/ansible-debug-print-variables/
- name: Print some ansibule distribution debug information
  vars:
    msg: |
        Ansible Distribution: {{ ansible_distribution }}
        Ansible Dist version: {{ ansible_distribution_version }}
  debug:
    msg: "{{ msg.split('\n') }}"
