---

- name: Install packages to allow apt to use a repository over HTTPS.
  apt:
    name: "{{ docker.packages.dependencies }}"
    state: present

- name: Add Docker's official GPG key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Set up the stable repository.
  apt_repository:
    repo: "deb [arch=amd64] \
           https://download.docker.com/linux/ubuntu \
           {{ ansible_distribution_release }} \
           stable"

- block:
  - name: Install docker engine-community packages.
    apt:
      name: "{{ docker.packages.docker_ce }}"
      state: present

  # ref. https://stackoverflow.com/questions/26394096/in-ansible-how-do-i-get-a-variable-with-the-name-of-the-user-running-ansible
  - name: Add user to docker group.
    user:
      #name: "{{ lookup('env', 'user') }}"
      name: "{{ ansible_env.SUDO_USER }}"
      groups: docker
      append: yes

  - name: Ensure docker service is enabled.
    service:
      name: docker
      state: started
      enabled: yes

  when: not ansible_check_mode
