---

common:
  packages:
    - make
    - git
    - vim
    - tree
    - colordiff
    - jq
    - acl
    - sshfs
    - nkf
  locale:
    packages:
      - language-pack-ja

docker:
  # ref. https://docs.docker.com/compose/install/#install-compose-on-linux-systems
  docker_compose_version: 1.25.5
  packages:
    # required dependencies for installing docker-ce.
    dependencies:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    docker_ce:
      - docker-ce
      - docker-ce-cli
      - containerd.io
