---

common:
  packages:
    - make
    - git
    - vim
    - tree
    - colordiff
    - jq
    - acl
    - nkf
    - zip
    - unzip
    - fzf
    - git-ftp
  locale:
    packages:
      - language-pack-ja
