name: Testing

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: Ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install ansible.
        run: /bin/bash scripts/install-ansible.sh

      - name: Run ansible debug role. (will be removed)
        run: ansible-playbook -i inventory/hosts.ini ubuntu-bionic.yml --diff --tags debug
