name: Testing

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install ansible.
        run: /bin/bash scripts/install-ansible.sh

      - name: Perform a syntax check on the playbook.
        run: ansible-playbook -i inventory/hosts.ini ubuntu-bionic.yml --syntax-check

      - name: Run ansible-playbook.
        run: ansible-playbook -i inventory/hosts.ini ubuntu-bionic.yml --diff
